apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    move2kube.konveyor.io/expose: "true"
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: kjanania-sample-service
  name: kjanania-sample-service
spec:
  replicas: 1
  selector:
    matchLabels:
      move2kube.konveyor.io/service: kjanania-sample-service
  strategy: {}
  template:
    metadata:
      annotations:
        move2kube.konveyor.io/expose: "true"
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: kjanania-sample-service
      name: kjanania-sample-service
    spec:
      containers:
        - image: sample-service:latest
          imagePullPolicy: Always
          name: kjanania-sample-service
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
