kind: ConfigMap
apiVersion: v1
metadata:
  name: sample-service
data:
  application.yaml: |-
    spring:

      datasource:
        url: jdbc:postgresql://${vcap.services.postgres-service.credentials.connection.postgres.hosts[0].hostname:postgresql}:${vcap.services.postgres-service.credentials.connection.postgres.hosts[0].port:5432}/${vcap.services.postgres-service.credentials.connection.postgres.database:sampledb}
        username: ${vcap.services.postgres-service.credentials.connection.postgres.authentication.username:user}
        password: ${vcap.services.postgres-service.credentials.connection.postgres.authentication.password:password}
      jpa:
        hibernate:
          ddl-auto: update
      flyway:
        locations: classpath:db/migration/{vendor}
        schemas:
          - APPLICATION
        defaultSchema: APPLICATION
        createSchemas: true
